models.py
from app import db
from flask_security import UserMixin, RoleMixin


post_tags = db.Table('post_tags',
                     db.Column('post_id', db.Integer, db.ForeignKey('posts.id')),
                     db.Column('tag_id', db.Integer, db.ForeignKey('tag.id'))
                     )


class Post(db.Model):
    __tablename__ = 'posts'
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(140))
    body = db.Column(db.Text)

    tags = db.relationship('Tag', secondary=post_tags, backref=db.backref('posts', lazy='dynamic'))


class Tag(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100))



roles_users = db.Table('roles_users',
                       db.Column('user_id', db.Integer(), db.ForeignKey('user.id')),
                       db.Column('role_id', db.Integer(), db.ForeignKey('role.id'))
                       )



class User(db.Model, UserMixin):
    id = db.Column(db.Integer(), primary_key=True)
    email = db.Column(db.String(100), unique=True)
    password = db.Column(db.String(255))
    active = db.Column(db.Boolean())
    roles = db.relationship('Role', secondary=roles_users, backref=db.backref('users', lazy='dynamic'))


class Role(db.Model, RoleMixin):
    id = db.Column(db.Integer(), primary_key=True)
    name = db.Column(db.String(100))

posts/forms.py
from wtforms import Form, StringField, TextAreaField

class PostForm(Form):
    title = StringField('Title')
    body = TextAreaField('Body')

app.py
from flask import Flask
from config import Configuration
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate, MigrateCommand
from flask_script import Manager

from flask_security import SQLAlchemyUserDatastore
from flask_security import Security


app = Flask(__name__)
app.config.from_object(Configuration)


db = SQLAlchemy(app)

migrate = Migrate(app, db)
manager = Manager(app)
manager.add_command('db', MigrateCommand)

# Blueprint
from posts.blueprint import posts
import view

app.register_blueprint(posts, url_prefix='/blog')


# Security
from models import User, Role
user_datastore = SQLAlchemyUserDatastore(db, User, Role)
security = Security(app, user_datastore)



if __name__ == '__main__':
    app.run()

posts/blueprint.py
from flask import Blueprint
from flask import render_template
from flask import request, url_for
from flask import redirect
from models import Post
from .forms import PostForm
from app import db
from flask_security import login_required



posts = Blueprint('posts', __name__, template_folder='templates')


@posts.route('/create', methods=['POST', 'GET'])
@login_required
def post_create():
    if request.method == 'POST':
        title = request.form['title']
        body = request.form['body']
        try:
            post = Post(title=title, body=body)
            db.session.add(post)
            db.session.commit()
        except:
            print('Error')

        return redirect(url_for('posts.index'))
    form = PostForm()
    return render_template('posts/post_create.html', form=form)


@posts.route('/edit/<int:id>', methods=['POST', 'GET'])
def post_edit(id):
    post = Post.query.filter(Post.id == id).first()

    if request.method == 'POST':
        form = PostForm(formdata=request.form, obj=post)
        form.populate_obj(post)
        db.session.commit()
        return redirect(url_for('posts.post_detail', id=post.id))

    form = PostForm(obj=post)
    return render_template('posts/post_edit.html', post=post, form=form)


@posts.route("/delete/<int:id>", methods=["POST"])
def post_delete(id):
    post = Post.query.filter(Post.id == id).first()
    db.session.delete(post)
    db.session.commit()
    return redirect(url_for('posts.index'))



@posts.route('/<int:id>')
def post_detail(id):
    post = Post.query.filter(Post.id == id).first()
    tags = post.tags
    return render_template('posts/post_detail.html', post=post, tags=tags)


@posts.route('/')
def index():
    q = request.args.get('q')
    if q:
        posts = Post.query.filter(Post.title.contains(q)).all()
    else:
        posts = Post.query.all()
    return render_template('posts/index.html', posts=posts)

posts/templates/posts/index.html
{% extends 'base.html' %}

{% block title %}
    Posts
{% endblock %}

{% block content %}
    {% for post in posts %}
        <a href="{{ url_for('posts.post_detail', id=post.id) }}">{{ post.title }}</a>
    {% endfor %}
{% endblock %}

posts/templates/posts/post_create.html
{% extends 'base.html' %}

{% block title %}
    Create post
{% endblock %}


{% block content %}
    <form action="{{ url_for('posts.post_create') }}" method="POST">

        {% for field in form %}
            <div class="form-group">
                {{ field.label(class='control-label') }}
                {{ field(class='form-control') }}
            </div>
        {% endfor %}
        <button type="submit" class="btn btn-info">Создать</button>
    </form>

{% endblock %}

posts/templates/posts/post_detail.html
{% extends 'base.html' %}

{% block title %}
post id {{ post.id }}
{% endblock %}


{% block content %}
    <h4>{{ post.title }}</h4>
    <p>{{ post.body }}</p>

    <div class="tags">
    {% for tag in tags %}
    <span class="badge badge-primary">{{ tag.name }}</span>
    {% endfor %}
    </div>

    <form method="POST" action="{{ url_for('posts.post_delete', id=post.id) }}">
    <button type="submit" class="btn btn-danger">Удалить</button>
    </form>

{% endblock %}

posts/templates/posts/post_edit.html
{% extends 'base.html' %}

{% block title %}
    Edit post
{% endblock %}


{% block content %}
    <form action="{{ url_for('posts.post_edit', id=post.id) }}" method="POST">

        {% for field in form %}
            <div class="form-group">
                {{ field.label(class='control-label') }}
                {{ field(class='form-control') }}
            </div>
        {% endfor %}
        <button type="submit" class="btn btn-info">Изменить</button>
    </form>

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Posts</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>

{% include 'header.html' %}

<div class="container">
    <div class="row">
        <h1>
            {% block title %}
            {% endblock %}
        </h1>
    </div>
    <div>
        {% block content %}
        {% endblock %}
    </div>

</div>

</body>
</html>

templates/header.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{{ url_for('index') }}">Projects</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{{ url_for('posts.index') }}">Posts</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('posts.post_create') }}">Create post</a>
            </li>
        </ul>
         <form class="form-inline my-2 my-lg-0" method="GET">
      <input class="form-control mr-sm-2" type="search"
             placeholder="Search" aria-label="Search" name="q" value="{{ request.args.get('q', '') }}">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
    </div>
</nav>

templates/index.html
{% extends 'base.html' %}

{% block title %}
    Index page
{% endblock %}

{% block content %}
    Content
{% endblock %}